### ISSUE TITLE
Need to fix Typescript definitions since Typescript 4.6

### ISSUE THREAD

**Issue by tomhanax** [knockout/knockout#2589]
Based on https://github.com/microsoft/TypeScript/issues/48150  and https://stackoverflow.com/questions/71319489/type-observablefalse-is-not-assignable-to-type-observableboolean I report that in the Typescript 4.6 the type definitions are leading to compile errors. As stated, the definitions were not correct but the type system was fixed and now the error surfaced.
To be concrete, it will be necessary to make small changes all over the place like this:

FROM:

```ts
function observable<T>(value: T): Observable<T>
{
  return undefined as any;  // the implementation is not important
}
```
TO:

```ts
function observable<T, U = any>(value?: T extends infer R ? R : U): unknown extends T ? Observable<U> : Observable<T>
{
  return undefined as any;  // the implementation is not important
}
```

**Comment by brianmhunt** [comment]
Excellent report, thanks for sharing.   I can't speak for the knockout.js types, but I'll add this to TKO as we move they typing forward.

**Comment by tomhanax** [comment]
@brianmhunt only FYI - according the new solution at original issue I have edited the "TO" part (I do not know if I notify you like this, sorry for bothering)

**Comment by mbest** [comment]
I added a comment to the TypeScript issue since I think TS can handle this situation better.

**Comment by mbest** [comment]
This was fixed in TypeScript: https://github.com/microsoft/TypeScript/pull/48380

**Comment by DevProLog** [comment]
Hi @mbest and @tomhanax ,

I use Knockout with typescript and am currently stuck using TS version 4.5.
Using higher versions of typescript (currently trying v4.8.4), I get unexpected errors.
Half of the errors are fixed by the more specific definition suggested by @tomhanax.

```typescript
//export function observable<T>(value: T): Observable<T>;
export function observable<T, U = any>(value?: T extends infer R ? R : U): unknown extends T ? Observable<U> : Observable<T>;
export function observable<T = any>(value: null): Observable<T | null>
```

E.g.: Without the fix, the following results in a typescript compiler error:

```typescript
AttestType: Observable<EAttestType> = ko.observable(EAttestType.Consultatie);
```

And, in order to please the TS compiler, would need to be changed to this:
```typescript
AttestType: Observable<EAttestType> = ko.observable<EAttestType>(EAttestType.Consultatie);
```
or this:
```typescript
AttestType: Observable<EAttestType> = ko.observable(EAttestType.Consultatie as EAttestType);
```

However, we still encounter other TS compiler errors, specifically related to types inheriting abstract classes in observables in the following form:

```typescript
export class ModalExistingPatientsComponentParams extends BaseComponentParams {
    ComponentViewModel: Observable<ModalExistingPatientsComponentViewModel | null> = observable<ModalExistingPatientsComponentViewModel | null>(null);

    constructor() {
        super();
    }
}

Property 'ComponentViewModel' in type 'ModalExistingPatientsComponentParams' is not assignable to the same property in base type 'BaseComponentParams'.
  Type 'Observable<ModalExistingPatientsComponentViewModel | null>' is not assignable to type 'Observable<BaseComponentViewModel | null>'.
    Types of parameters 'value' and 'value' are incompatible.
      Type 'BaseComponentViewModel | null' is not assignable to type 'ModalExistingPatientsComponentViewModel | null'.
```

TS says that it cannot assign the base type to the derived type, which is correct.
But the question is, why is it trying to do this in the first place?
I think that the knockout ts definitions are not supporting working with derived types in observables.

Here is a simplified playground detailing the issue:
[Playground link](https://www.typescriptlang.org/play?ts=4.8.4#code/JYOwLgpgTgZghgYwgAgPICMDO0Bud0A2EAPACoB8yA3gFDLIAUAlAFzKkDcdjeBArhDalWyOCACeXAL40aAejnIAJhAQE4UFDD4gEYYAHsQyA1lz4iZcg14ChIjNih5CJClxVqNWnXsPHTJxdLUmQAXlEJa1tBZBA+AgIHM2cLN2QAHziEgnIaT3VNZG1dfSMTFOC3ABpkAFVwyPFouH4IAH4hZAgAD0gQJUxkUBhoZAAlZHaJ5DY6kR0AaxADAHdjXv7B9im0SrTiOso2R3NXKy5ZXoAHAygwUSwwKEQHr0whgCE4bABhAwAtrcQBBwAA1YAQVYAWQMKgI1G49AAkpgADIGOBKUAAcxO+3O6AMBiIYkoEUCZyIDGeAiYXHoKMw-xAmFpeggSnxQQORJJEDJjUpqVcDHgBGw9NkjOQCCMbKgfD0dwY1w0cABmDY3z+gOBoLAAAV1ZqmIiZTK1S9NQA6f5AowGiFQ2HwmkAC2AmClMpkSOQiwMABEIJgkAMxGBmXqiJBGsxwpRaBbGWBPZgbaiWQqlZAlDTFRAfYyZH6bncHvgFa9ZeoPsgdRB7frwABlVRlEDOmFwiAI5OM1EYrG47lUkh80kgckVHmi2lFhmD6Os9l5sciyyTgXToUE6niyWXGVy1eK5VQVUmrUNn5NvWOtsd-zG63e80p5BWjUZ5uPsDtn4Rjdq6fYel6xb0H6MqBiGYagkokbRkCsYoBECZhEm-oymmXqZiuOYcvmC6QcgpZXD0tz3I81Z6LWPxfHef4guAr4-h+9BVs8NbMU6kI9vCG5VMQja8eC-GgQiWTxIk5DSBRVGVk8Lx0e8jG6g6LEAc+RhsZqHE0dxdFidpQFdhJvYEEJByiQ+WmAZ2IGWZk2SyUunHKTWr4GiZTmCbeGktmAfl9vJNDltRanICZLKQH0BnfpqACE2pMXZBp6UMWS2ZpBoOS+17Hoyp6EWAKrYYyiU3jlQWZS5NX-vlunXv6ZoDimuEZlVjRVe5ZE0GWlEVvR9auq0ACiPRevoIA4sa+gGshtXXt0fQIep965axK3tdF6XiS6lnWecY0EJN024vNkLgEt-4hVJrm5Huc6WKd51spdcALTdvkWfCLkybkDCA1K-olWuKptRV9CYHw1zQMwfXkeFQ2RXWQxvVNH2zVdi2-Yd-2bOtAWbUF90GUYrZwDgEC4+AvytAQ6CIIsKWMBhlA4AYwBKGa0k5H1ACCYCQGypDiPDx2WONwui2A4vwzOwpVAwMsi6G8sSxANqCwM0CLtKxXyhDl5VWwmMXTjX3XVGJmZVDn7ILD8Om9epHIxFDygnwALIGrcsKygu26yomjVP6qCzaGCCeosaYQDz4cymC0DXEQEA4osOjYjiEBJ4y2YJGA1sQANshAA)

**Comment by tomhanax** [comment]
I think this is again the problem with variance: https://github.com/microsoft/TypeScript/issues/48150#issuecomment-1060363694

**Comment by DevProLog** [comment]
So, in your eyes, do we need a fix in TS or in Knockout definitions?

**Comment by tomhanax** [comment]
To be honest, I really do not know, I am "only the user" and have no idea about these "inner workings"... :( Only tried to point out possible explanation of the problem. But I know this does not solve anything for "us" (knockout.js users), it is only something about wrong variance in some type theory, which, bluntly said, I do not know nothing about (and do not care either) - until compiler yells at me. So what to do next - practically? I'd be glad to know, too... We fight this time to time in latest TS version, sometimes we "force cast" things and make the compiler quiet. As "only the user" I feel, that this is the more "theoretical" thing in the TS, so we wait that maybe someday, somehow, it will fix itself... ;) And maybe we will try TKO someday.
